[tool.poetry]
name = "dump-env"
version = "0.2.2"
description = "A utility tool to create .env files"

license = "MIT"

authors = [
  "Nikita Sobolev <mail@sobolevn.me>"
]

readme = "README.md"  # Markdown files are supported

repository = "https://github.com/sobolevn/dump-env"
homepage = "https://github.com/sobolevn/dump-env"

keywords = [
  "dotenv",
  ".env",
  "tempaltes",
  "secrets",
  "CI/CD"

]

classifiers = [
  "Development Status :: 5 - Production/Stable",
  "Environment :: Console",
  "Intended Audience :: Developers",
  "License :: OSI Approved :: MIT License",
  "Operating System :: OS Independent",
  "Programming Language :: Python",
  "Programming Language :: Python :: 2.7",
  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3.5",
  "Programming Language :: Python :: 3.6",
  "Programming Language :: Python :: Implementation :: CPython"
]

[tool.poetry.dependencies]
python = "^2.7 || ^3.6"  # taken from setup.py

# all the versions below are defined with poetry add --dev DEPENDENCY_NAME
[tool.poetry.dev-dependencies]
pycodestyle = "^2.4"
pytest-cov = "^2.6"
pytest-isort = "^0.2.1"
flake8-builtins = "^1.4"
flake8-commas = "^2.0"
flake8-quotes = "^1.0"
flake8-pep3101 = "^1.2"
flake8-comprehensions = "^1.4"
flake8-blind-except = "^0.1.1"
flake8-docstrings = "^1.3"
flake8-string-format = "^0.2.3"
flake8-coding = "^1.3"
flake8-module-name = "^0.1.5"
flake8-pytest = "^1.3"
pep8-naming = "^0.7.0"
pytest = "^3.8"
pytest-flake8 = "^1.0"
